enableEmoji = true
enableRobotsTXT = true
title = "Pitlord INC."
baseURL = "https://pitlords.com"
disqusShortname = "pitlords"
paginate = 9
languageCode = "en-us"
googleAnalytics = ""
summaryLength = "10"

[permalinks]
blogs = "/blog/:slug/"
products = "/products/:slug/"
pages = "/:slug"

[author]
homepage = "https://github.com/goldcoders"
name = "Pitlord"
avatar = "/images/avatar.svg"