enableEmoji = true
enableRobotsTXT = true
title = "Goldcoders"
baseURL = "https://goldcoders.dev"
googleAnalytics = ""
disqusShortname = "goldcoders"
languageCode = "en-us"
summaryLength = "10"
paginate = 9

[permalinks]
blogs = "/blog/:slug/"
products = "/products/:slug/"
pages = "/:slug"

[privacy]

[privacy.disqus]
disable = true

[privacy.googleAnalytics]
disable = false

[privacy.instagram]
disable = true

[privacy.twitter]
disable = true

[privacy.vimeo]
disable = true

[privacy.youtube]
disable = true

[author]
homepage = "https://github.com/goldcoders"
name = "Goldcoders"
avatar = "/images/avatar.svg"

[build]
noJSConfigInAssets = false
useResourceCacheWhen = "fallback"
writeStats = true