github_user = "goldcoders"
mainSections = ["blog", "products"]
copyright = "Copyright © 2024, GOLDCODERS™️., all rights reserved."
github_banner = true
github_repo = "https://github.com/thrift-shop-site/theme"
favicon = "/images/transparent_logo.png"
description = "The Most Affordable Ecommerce Site For Filipino Online Seller Startups"

[gtm]
enable = false
id = ""

[logo]
image = "/images/transparent_logo.png"
height = "14"

[brand]
enable = true
name = "Goldcoders"
font = "steel"
color = "brand"
shade = ""

[cover_photo]
color = "white"
shade = ""
font = "steel"

[crispchat]
id = ""
enable = false

[placeholder]
cover_photo = "https://cdn.pixabay.com/photo/2015/03/26/09/40/business-suit-690048_960_720.jpg"
post = "https://via.placeholder.com/760x450"

[tag]
name = "Dev"
font = "steel"
color = "white"
shade = ""